### PR TITLE
Fix: Remove readonly status before removing and renaming

### LINKED ISSUE #363: Read-only files cannot be removed in Windows

### PR DESCRIPTION
**Pull request by jLantxa**

### CODE REVIEW

File: core/src/backend/localfs.rs [hunk 1]
```diff
@@ -126,32 +129,38 @@ impl StorageBackend for LocalFS {
...
     fn rename(&self, from: &Path, to: &Path) -> Result<()> {
         let fullpath_from = self.full_path(from);
         let fullpath_to = self.full_path(to);
+
+        // On Windows, the source must be writable to be renamed/moved
+        let _ = self.set_readonly_status(&fullpath_from, false);
+
         std::fs::rename(fullpath_from, fullpath_to).with_context(|| {
             format!(
-                "Could not rename '{}' to '{}' in local backend",
```
Comment (jLantxa) [inline core/src/backend/localfs.rs:150]: Dejar comentario.
